name: World1-6Economy
main: World16Economy.Main.Main
version: 1
depends: [Vault]

commands:
  bal:
    aliases:
      - money
  eco:

permissions:
  world16.bal:
    description: Allows you to do bal command
    default: true
  world16.bal.other:
    description: Allow you to see other balances of other players
    default: false

  world16.eco:
    description: Allows you to do eco command
    default: true
  world16.eco.give:
    description: Allows you to do eco give command
    default: false
  world16.eco.take:
    description: Allows you to do eco take command
    default: false
  world16.eco.set:
    description: Allows you to do eco set command
    default: false
  world16.eco.reset:
    description: Allows you to do eco reset command
    default: false
  world16.eco.op:
    description: Allows you to do eco admin commands
    default: true
    children:
      world16.eco.give: true
      world16.eco.take: true
      world16.eco.set: true
      world16.eco.reset: true