name: World1-6Economy
main: com.andrew121410.mc.world16economy.World16Economy
version: 1.0
depends: [ Vault ]
api-version: 1.16

commands:
  bal:
    aliases:
      - money
  eco:

permissions:
  world16.bal:
    description: Allows you to do bal command
    default: true
  world16.bal.other:
    description: Allow you to see other balances of other players
    default: true

  world16.eco:
    description: Allows you to do eco command
    default: op
  world16.eco.give:
    description: Allows you to do eco give command
    default: op
  world16.eco.take:
    description: Allows you to do eco take command
    default: op
  world16.eco.set:
    description: Allows you to do eco set command
    default: op
  world16.eco.reset:
    description: Allows you to do eco reset command
    default: op
  world16.eco.debug:
    description: Allows you to do eco reset command
    default: op
  world16.eco.op:
    description: Allows you to do eco admin commands
    default: op
    children:
      world16.eco.give: true
      world16.eco.take: true
      world16.eco.set: true
      world16.eco.reset: true
      world16.eco.debug: true